### ISSUE TITLE
The go.mod file for the module providing named packages contains one or....

### ISSUE THREAD

**Issue by mambrus** [MichaelMure/git-bug-migration#10]
Tried to test the bridging to gitlab which failed. Read some comment about the same or similar bug where user is asked if the bug still remains as it's very old: https://github.com/MichaelMure/git-bug/issues/906

I can't figure out the version as:
```bash
$ git bug version
git-bug version: -dev-
```
So guessing that it's old despite having run ` go install`  again. Did the following 
```bash
$ sudo rm -rf ~/go                                                    
$ go install github.com/MichaelMure/git-bug@latest

$ git bug termui                                                      
Building identity cache... Error: invalid ref: outdated repository format, please use https://
github.com/MichaelMure/git-bug-migration to upgrade
```
The link is bad but figured out it must be:
```bash
$ go install github.com/MichaelMure/git-bug-migration@latest 
go: downloading github.com/MichaelMure/git-bug-migration v0.3.3
go: github.com/MichaelMure/git-bug-migration@latest (in github.com/MichaelMure/git-bug-migration@v0.3.3):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
$ git-bug-migration                                                
-bash: git-bug-migration: command not found
```
I don't know `go` let alone it's quirks. Completely stuck and have no idea what to do.

**Comment by MichaelMure** [comment]
> I can't figure out the version as:
> 
> ```shell
> $ git bug version
> git-bug version: -dev-
> ```
> 
> So guessing that it's old despite having run ` go install` again. Did the following

The problem being that the makefile set those values, so that's not done when using `go install`.  A bit annoying, I should change that.

> I don't know go let alone it's quirks. Completely stuck and have no idea what to do.

It's not go, it's the dirty thing I've done in the `go.mod` file. I'll fix it.

**Comment by MichaelMure** [comment]
Should be fixed with https://github.com/MichaelMure/git-bug-migration/releases/tag/v0.3.4
